import webb from "../assets/jameswebb.webp";
import nasaeyes from "../assets/nasaeyes.jpg";
import mars from "../assets/mars.jpg";
import bingo from "../assets/bingo.jpg";
import googleskymap from "../assets/googleskymap.jpg";

export const data = [
{title: "Nasa`s Eyes", image: nasaeyes, about: "O Nasa`s Eyes incorpora informações de orientação vindas diretamente da base de dados da NASA. Ou seja, se você quer ver como um determinado satélite chegou até as luas de Saturno, você pode.", description: "Sistema Solar Interativo", link: "https://www.google.com"},
{title: "Telescópio WEBB", image: webb, about: "Imagens fantasticas do supertelescópio James Webb mostram o Universo como nunca antes visto. Foi um presente de US$ 10 bilhões para o mundo. Uma máquina que mostraria nosso lugar no Universo.", description: "Telescópio James Webb", link: ""},
{title: "Planeta Vermelho", image: mars, about: "O Dia do Planeta Vermelho comemora-se a 28 de novembro. Este dia celebra o lançamento da nave espacial Mariner 4, responsável pela receção e pelo envio das primeiras fotografias da superfície marciana para a Terra, a 28 de novembro de 1964.", description: "Dia do Planeta Vermelhor\n28 de Novembro.", link: ""},
{title: "Conheça o BINGO", image: bingo, about: "O BINGO é um radiotelescópio projetado para fazer a primeira descrição de Oscilações Acústicas de Bárions, que são ondas geradas pela interação dos átomos com a radiação no inicio do Universo, e que podem ser observadas na faixa de radiofrequência.", description: "Conheça o Projeto Bingo", link: ""},
{title: "Google Sky Maps", image: googleskymap, about: "Google Sky Maps é um mapa celestial que mostra objetos como estrelas, constelações, galáxias, planetas ou a lua da Terra.", description: "Descubra e busque as estrelas, viage pelo tempo e mais.", link: ""},

{title: "História da água", image: "https://i.ytimg.com/vi/xCKOtzJUggE/hq720.jpg?sqp=-oaymwEdCJUDENAFSFXyq4qpAw8IARUAAIhCcAHAAQbQAQE=&rs=AOn4CLCpwoTWsy8R189Z1OOd_g_bZ6NlVQ", about: "O quão velha é a água que você bebe.", description: "O quão velha é a água que você bebe.", link: "https://www.youtube.com/shorts/xCKOtzJUggE"},
{title: "Cone antigravidade", image: "https://i.ytimg.com/vi/QVLt-x3qjKM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDimH0kj6KfJLOUOP6xrkg-ewquFA", about: "Aprenda a fazer um cone antigravidade.", description: "Aprenda a fazer um cone antigravidade.", link: "https://www.youtube.com/watch?v=QVLt-x3qjKM"},
{title: "DESLIGAMOS a GRAVIDADE", image: "https://i.ytimg.com/vi/SWgwUQgHQds/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDsFPlgdg2IQsEXd8qSIKiKL7GBCQ", about: "DESLIGAMOS a GRAVIDADE? Ilusão IMPRESSIONANTE", description: "DESLIGAMOS a GRAVIDADE? Ilusão IMPRESSIONANTE", link: "https://www.youtube.com/watch?v=SWgwUQgHQds"},
{title: "Eclipse anular solar", image: "https://jornaldaparaiba.com.br/wp-content/uploads/2023/08/jongsun-lee-F-pSZO_jeE8-unsplash-scaled.jpg", about: "Eclipse anular solar: os melhores lugares na Paraíba para ver o fenômeno em outubro.", description: "Eclipse anular solar: os melhores lugares na Paraíba para ver o fenômeno em outubro.", link: "https://jornaldaparaiba.com.br/tecnologia/melhores-lugares-na-paraiba-para-ver-o-eclipse-anular-solar/"},
{title: "A Velocidade da luz", image: "https://i.ytimg.com/vi/C_jt0FiQE3s/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhHIGUoOTAP&rs=AOn4CLC43FtBG9z1KKpKwwo19QIdtXSQpA", about: "Carl Sagan - A velocidade da luz- Dublado em Português!", description: "Carl Sagan - A velocidade da luz- Dublado em Português!.", link: "https://www.youtube.com/watch?v=C_jt0FiQE3s&feature=youtu.be"},

{title: "6 apps para observar o céu", image: "https://socientifica.com.br/wp-content/uploads/2022/08/pexels-lucas-pezeta-2034892-1536x1024.jpg.webp", about: "Conheça 6 aplicativos para observar o céu com funções diferentes.", description: "Conheça 6 aplicativos para observar o céu com funções diferentes.", link: "https://socientifica.com.br/aplicativos-para-observar-o-ceu/"},
{title: "Bolhas de Sabão Gigantes", image: "https://i.ytimg.com/vi/wwg35vDg4fg/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC88DeFCOI3LaH4CMkNA1R0D1lpFA", about: "Video: Saida o Segredo das Bolhas de Sabão Gigantes", description: "O Segredo das Bolhas de Sabão Gigantes", link: "https://www.youtube.com/watch?v=wwg35vDg4fg"},
{title: "Duplo Cone e Disco 'Maluco'", image: "https://i.ytimg.com/vi/U0CCs8L-P2o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDP-s8UnGQQeOoBp8pONWQ_Tgw4Zg", about: "Duplo Cone e Disco 'Maluco'", description: "Duplo Cone e Disco Maluco'", link: "https://www.youtube.com/watch?v=U0CCs8L-P2o"},
{title: "A luz que faz curva na água", image: "https://i.ytimg.com/vi/F69tWoZa4ic/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAN2gCSCUtavEjABSffQO9eqblf9w", about: "A luz que faz curva na água (EXPERIÊNCIA de FÍSICA)", description: "A luz que faz curva na água (EXPERIÊNCIA de FÍSICA)", link: "https://www.youtube.com/watch?v=F69tWoZa4ic"},
{title: "Bolhas flutuando com eletricidade", image: "https://i.ytimg.com/vi/zH8EiGKt_BE/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAur5-te2UeoTm0Rtes-d4Nd2N8nw", about: "Saiba como fazer BOLHAS que FLUTUAREM com ELETRICIDADE", description: "Saiba como fazer BOLHAS que FLUTUAREM com ELETRICIDADE", link: "https://www.youtube.com/watch?v=zH8EiGKt_BE"},

{title: "Primeiras Imagens do James Webb", image: "https://i.ytimg.com/vi/0X57Hg7WX_E/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBPD6V-BeDu7129s-o3TH5G_jWZJw", about: "As Primeiras Imagens do James Webb vão mudar a astronomia.", description: "As Primeiras Imagens do James Webb vão mudar a astronomia.", link: "https://www.youtube.com/watch?v=0X57Hg7WX_E"},

]
